name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ## What's Changed
          
          * Docker image: `ghcr.io/quincymillerdev/ilograph-mcp-server:${{ github.ref_name }}`
          * Latest: `ghcr.io/quincymillerdev/ilograph-mcp-server:latest`
          
          ## Installation
          
          ```json
          {
            "mcpServers": {
              "ilograph": {
                "command": "docker",
                "args": ["run", "-i", "--rm", "ghcr.io/quincymillerdev/ilograph-mcp-server:${{ github.ref_name }}"]
              }
            }
          }
          ```
          
          See README.md for full installation instructions.
        draft: false
        prerelease: false 